version: '3.8'

services:
  db:
    container_name: db
    build: ./Dockerfile-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  kotiki-app:
    build: ./Dockerfile-app
    container_name: kotiki-app
    depends_on:
      - db
    #image: ubuntu:22.04
    stdin_open: true
    tty: true
    ports:
      - '8000:8000'

volumes:
  db:
    driver: local