FROM openjdk:17-alpine
ADD build/libs/kotiki-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
RUN export PROJECT_PATH=$(pwd)
ARG DATABASE_URL
ARG JWT_ACCESS_TOKEN_SECRET
ARG JWT_REFRESH_TOKEN_SECRET
ARG PGDATABASE
ARG PGHOST
ARG PGPASSWORD
ARG PGPORT
ARG PGUSER
ARG SERVER_ADDRESS
ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]